# ---------- BUILD ----------
FROM node:24-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

ARG PR_PATH

RUN yarn build -- --base-href=/${PR_PATH}/ --deploy-url=/${PR_PATH}/

# ---------- NGINX ----------
FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist/meu-app/browser /usr/share/nginx/html
