services:
  postgres:
    image: postgres:16
    restart: always
    env_file:
      - /opt/app/configs/.env.preview
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.preview
      args:
        APP_MAJOR_VERSION: ${APP_MAJOR_VERSION:-0}
        APP_MINOR_VERSION: ${APP_MINOR_VERSION:-1}
        APP_PATCH_VERSION: ${APP_PATCH_VERSION:-0}
    restart: always
    depends_on:
      - postgres
    env_file:
      - /opt/app/configs/.env.preview
    environment:
      RAILS_ENV: preview
      SCRYFALL_DATA_DIR: /scryfall
    volumes:
      - /opt/app/scryfall:/scryfall
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-${PR_NUMBER}.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/pr-${PR_NUMBER}/api`)"
      - "traefik.http.routers.api-${PR_NUMBER}.entrypoints=websecure"
      - "traefik.http.routers.api-${PR_NUMBER}.tls.certresolver=le"
      - "traefik.http.routers.api-${PR_NUMBER}.middlewares=api-${PR_NUMBER}-strip"
      - "traefik.http.middlewares.api-${PR_NUMBER}-strip.stripprefix.prefixes=/pr-${PR_NUMBER}"
      - "traefik.http.services.api-${PR_NUMBER}.loadbalancer.server.port=3000"
    networks:
      - postgres
      - proxy

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.preview
    restart: always
    depends_on:
      - postgres
    env_file:
      - /opt/app/configs/.env.preview
    environment:
      RAILS_ENV: preview
      SCRYFALL_DATA_DIR: /scryfall
    volumes:
      - /opt/app/scryfall:/scryfall
    command: ./bin/jobs
    networks:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.preview
      args:
        PR_PATH: pr-${PR_NUMBER}
    restart: always
    env_file:
      - /opt/app/configs/.env.preview
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front-${PR_NUMBER}.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/pr-${PR_NUMBER}`)"
      - "traefik.http.routers.front-${PR_NUMBER}.entrypoints=websecure"
      - "traefik.http.routers.front-${PR_NUMBER}.tls.certresolver=le"
      - "traefik.http.routers.front-${PR_NUMBER}.middlewares=front-${PR_NUMBER}-strip"
      - "traefik.http.middlewares.front-${PR_NUMBER}-strip.stripprefix.prefixes=/pr-${PR_NUMBER}"
      - "traefik.http.services.front-${PR_NUMBER}.loadbalancer.server.port=80"
    networks:
      - proxy

volumes:
  pgdata:

networks:
  postgres:
  proxy:
    external: true
