services:
  postgres:
    image: postgres:16
    restart: always
    env_file:
      - /opt/app/configs/.env.production
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    networks:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        APP_MAJOR_VERSION: ${APP_MAJOR_VERSION:-0}
        APP_MINOR_VERSION: ${APP_MINOR_VERSION:-1}
        APP_PATCH_VERSION: ${APP_PATCH_VERSION:-0}
    restart: always
    depends_on:
      - postgres
    env_file:
      - /opt/app/configs/.env.production
    environment:
      RAILS_ENV: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-prod.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/${PATH_PREFIX}/api`)"
      - "traefik.http.routers.api-prod.entrypoints=websecure"
      - "traefik.http.routers.api-prod.tls.certresolver=le"
      - "traefik.http.routers.api-prod.middlewares=api-prod-strip"
      - "traefik.http.middlewares.api-prod-strip.stripprefix.prefixes=/${PATH_PREFIX}"
      - "traefik.http.services.api-prod.loadbalancer.server.port=80"
    networks:
      - postgres
      - proxy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - /opt/app/configs/.env.production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front-prod.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/${PATH_PREFIX}`)"
      - "traefik.http.routers.front-prod.entrypoints=websecure"
      - "traefik.http.routers.front-prod.tls.certresolver=le"
      - "traefik.http.services.front-prod.loadbalancer.server.port=80"
    networks:
      - proxy

volumes:
  pgdata_prod:

networks:
  postgres:
  proxy:
    external: true
