version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.staging
    restart: always
    depends_on:
      - postgres
    environment:
      RAILS_ENV: staging
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/app_pr_${PR_NUMBER}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-${PR_NUMBER}.rule=Host(`viniciusfreire.dev.br`) && PathPrefix(`/pr-${PR_NUMBER}/api`)"
      - "traefik.http.routers.api-${PR_NUMBER}.entrypoints=websecure"
      - "traefik.http.routers.api-${PR_NUMBER}.tls.certresolver=le"

      - "traefik.http.services.api-${PR_NUMBER}.loadbalancer.server.port=3000"
    networks:
      - postgres
      - proxy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.staging
      args:
        PR_PATH: pr-${PR_NUMBER}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front-${PR_NUMBER}.rule=Host(`viniciusfreire.dev.br`) && PathPrefix(`/pr-${PR_NUMBER}`)"
      - "traefik.http.routers.front-${PR_NUMBER}.entrypoints=websecure"
      - "traefik.http.routers.front-${PR_NUMBER}.tls.certresolver=le"
      - "traefik.http.routers.front-${PR_NUMBER}.middlewares=front-${PR_NUMBER}-strip"

      - "traefik.http.middlewares.front-${PR_NUMBER}-strip.stripprefix.prefixes=/pr-${PR_NUMBER}"

      - "traefik.http.services.front-${PR_NUMBER}.loadbalancer.server.port=80"
    networks:
      - proxy

volumes:
  pgdata:

networks:
  postgres:

  proxy:
    external: true

