source "https://rubygems.org"

gem "rails", "~> 8.0.2", ">= 8.0.2.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "jbuilder"
gem "bcrypt", "~> 3.1.7"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem "bootsnap", require: false
gem "thruster", require: false
gem "rack-cors"
gem "rails-i18n", "~> 8.0.0"
gem "http"
gem "yajl-ffi", require: "yajl/ffi"
gem "kaminari"
gem "jwt"
gem "rack-attack"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "dotenv-rails"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "pry-rails"
  gem "rspec-rails", "~> 8.0.0"
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers"
  gem "ruby-lsp-rspec", require: false
  gem "ruby-lsp", require: false
  gem "timecop"
end
