name: Preview Environment

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Set PR variables
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "PR_ACTION=${{ github.event.action }}" >> $GITHUB_ENV
          echo DEPLOY_TOKEN=${{ secrets.DEPLOY_TOKEN }} >> $GITHUB_ENV

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: vinicius
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export PR_NUMBER=$PR_NUMBER
            export BRANCH=$BRANCH
            export DEPLOY_TOKEN=$DEPLOY_TOKEN

            echo "Deploying preview PR-${PR_NUMBER}"

            cd /opt/app

            if [ $PR_ACTION" = "closed" ]; then
              echo "Removing preview PR-${PR_NUMBER}"

              docker compose \
                -f pr-${PR_NUMBER}/docker-compose.staging.yml \
                --project-name pr-${PR_NUMBER} \
                down -v
              rm -rf pr-${PR_NUMBER}
              exit 0
            fi

            # Clonar ou atualizar repositório
            if [ ! -d "pr-${PR_NUMBER}" ]; then
              git clone https://$DEPLOY_TOKEN@github.com/vinifmatos/meu-app.git pr-${PR_NUMBER}
            fi

            cd pr-${PR_NUMBER}
            git fetch origin
            git checkout ${BRANCH}
            git pull origin ${BRANCH}

            docker compose -f docker-compose.staging.yml \
              --project-name pr-${PR_NUMBER} down
            docker compose -f docker-compose.staging.yml \
              --project-name pr-${PR_NUMBER} up -d --build
